config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'static_pages#index'
  get '/navbar', to: 'static_pages#navbar'
  get '/footer', to: 'static_pages#footer'
  get '/login', to: 'static_pages#login_form'
  get '/signup', to: 'static_pages#signup_form'
  get '/resetpassword', to: 'static_pages#forgotten_password_form'
  get '/banner', to: 'static_pages#banner'
  get '/cards', to: 'static_pages#cards'
  get '/comments', to: 'static_pages#comments'
  get '/kitui', to: 'static_pages#kitui'

  post '/', to: 'static_pages#index'
  post '/navbar', to: 'static_pages#navbar'
  post '/footer', to: 'static_pages#footer'
  post '/login', to: 'static_pages#login_form'
  post '/signup', to: 'static_pages#signup_form'
  post '/resetpassword', to: 'static_pages#forgotten_password_form'
  post '/banner', to: 'static_pages#banner'
  post '/cards', to: 'static_pages#cards'
  post '/comments', to: 'static_pages#comments'
  post '/kitui', to: 'static_pages#kitui'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def navbar
  end

  def footer
  end

  def login_form
  end

  def signup_form
  end

  def banner
  end

  def comments
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteMolecules</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/banner.html.erb
<!DOCTYPE html>
<html>

	<head>
		<title>Banner</title>
		<link rel="stylesheet" type="text/css" href="style.css">
	</head>




<div class="jumbotron">
  <h1 class="display-3"><b> Welcome on eventbrite </b></h1>
  <p class="lead">This plateform will allow you organize or participate to the best parties in the country</p>
  <hr class="my-4">
  <p>You just have to register, for free!</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>

<br/> <br/> <br/>

    <div class="jumbotron-small">
    	<div class="container">
      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-8 col-md-7 col-sm-6">
            <h1>Titre de ma page</h1>
            <p class="lead">Bla bla bli blo blu</p>
          </div>
      
        </div>
      </div>
    </div>
  </div>
  </html>

app/views/static_pages/cards.html.erb
<br><h1> Cartes d'évenements </h1> <br/> <br/>

<div class="card-columns">

  <div class="card image-bottom">
    <h5 class="card-title">Card title</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small> <button type="button" class="right btn btn-outline-secondary">Go to the event</button></p>
    <img class="card-img" src="http://infoblancosobrenegro.com/media/W1siZiIsIm5vdGljaWFzLzEwOTYxL2ZvdG8tNzkzMy5qcGVnIl0sWyJwIiwidGh1bWIiLCI4MDB4Il1d/fiestas.jpg?sha=088b4ff4854316d1" alt="Card image">
  </div>

  
  <div class="card image-top">
    <img class="card-img-top" src="https://cdnvos.lavoz.com.ar/sites/default/files/styles/width_1072/public/fiestas_1.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title that wraps to a new line</h5>
      <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small> <button type="button" class="right btn btn-outline-secondary">Go to the event</button></p>
    </div>
  </div>
 

  <div class="card image-top">
    <img class="card-img-top" src="https://salacascoantiguo.com/wp-content/uploads/Casco-Antiguo-Fiestas-y-Eventos-2.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
     <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small> <button type="button" class="right btn btn-outline-secondary">Go to the event</button></p>
    </div>
  </div>
  
  <div class="card bg-primary text-white text-center p-3">
    <blockquote class="blockquote mb-0">
      <p>FIND THE BEST EVENTS IN TOWN !</p>
    </blockquote>
  </div>
  
 
  <div class="card image-bottom">
     <h5 class="card-title">Card title</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small> <button type="button" class="right btn btn-outline-secondary">Go to the event</button></p>
    <img class="card-img" src="http://infoblancosobrenegro.com/media/W1siZiIsIm5vdGljaWFzLzEwOTYxL2ZvdG8tNzkzMy5qcGVnIl0sWyJwIiwidGh1bWIiLCI4MDB4Il1d/fiestas.jpg?sha=088b4ff4854316d1" alt="Card image">
  </div>


  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small>
      <button type="button" class="right btn btn-outline-secondary">Go to the event</button></p>
    </div>
  </div>

  <div class="card">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small> <button type="button" class="right btn btn-outline-secondary">Go to the event</button></p>
      </div>
    </div>
  </div>


<br/><h1> Cartes de participation </h1> <br/> 

<div class="list-group">
  <a href="#" class="list-group-item list-group-item-action active">
    Participants
  </a>
  <a href="#" class="list-group-item list-group-item-action">Le gars là-bas
  </a>
    <a href="#" class="list-group-item list-group-item-action">Cette meuf
  </a>
    <a href="#" class="list-group-item list-group-item-action">Lui aussi
  </a>
  <a href="#" class="list-group-item list-group-item-action disabled">Vous-même
  </a>
</div>



<br/><h1> Cartes de villes </h1> <br/> 

<div class="card-deck">
  <div class="card">
    <img src="https://parissecret.com/wp-content/uploads/2017/11/featmontnarte.png" class="card-img-top" alt="Paris">
    <div class="card-body">
      <h5 class="card-title">Paris</h5>
      <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>

  <div class="card">
    <img src="https://hips.hearstapps.com/hbu.h-cdn.co/assets/17/15/beach-town-color-valparaiso-chile.jpg?crop=1.00xw:0.376xh;0,0.0256xh&resize=1200:*" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Valparaiso</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>

  <div class="card">
    <img src="https://www.downtownchico.com/webart/customtext/62c.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Chico</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
</div>

app/views/static_pages/comments.html.erb
<body>
  <div class="comment">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <br/>
        <h5 class="modal-title">Comments</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <p><textarea class="story" name="story" rows="5" cols="33"> Please write your comment here 
      </textarea></p>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Submit</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

<div class="list-group">
  <a href="#" class="list-group-item list-group-item-action active">
    Commentaires
  </a>

  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Joe la fripouille</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small class="text-muted">modifié hier à 14h52</small>
  </a> 

  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Lucky Luke</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small class="text-muted">modifié il y a 5 secondes</small>
  </a>

   <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Jessy James</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
  
  </a>
</div>



</body>

app/views/static_pages/footer.html.erb
<!DOCTYPE html>
<html>

	<head>
		<title>Banner</title>
		<link rel="stylesheet" type="text/css" href="style.css">
	</head>

<body>
<!-- Footer -->
<footer class="page-footer font-small blue pt-4">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">All you need to know</h5>
        <p>If you have any questions about eventbrite (almost) every answer is here</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Who are we?</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Team</a>
          </li>
          <li>
            <a href="#!">Project</a>
          </li>
          <li>
            <a href="#!">Ambition</a>
          </li>
          <li>
            <a href="#!">Our future</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Why we are the best</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Your life before</a>
          </li>
          <li>
            <a href="#!">Your life now</a>
          </li>
          <li>
            <a href="#!">Your life in the future</a>
          </li>

        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>


  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3"> © 2019 Copyright Eventbrite-Maowaw THP
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
</body>

app/views/static_pages/forgotten_password_form.html.erb
<head>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <link rel="stylesheet" type="text/css" href="style.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>

<body>

<center>
 <div class="form card">
    <h5 class="card-header info-color white-text text-center py-4">
      <strong>You can reset your password here.</strong> 
    </h5>        <br>    <br>

    <div class="card-body px-lg-5 pt-0">
      <form id="register-form" role="form" autocomplete="off" method="post">
     
       <div class="form-group">
         <div class="input-group">
           <span class="input-group-addon"><i class="glyphicon glyphicon-envelope color-blue"></i></span>
           <input id="email" name="email" placeholder="email address" class="form-control"  type="email">
         </div>
       </div>

     <div class="form-group">
       <input name="recover-submit" class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0" value="Reset Password"type="submit">
     </div>
     
     <input type="hidden" class="hide" name="token" id="token" value=""> 

  </form>

    

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>

	<head>
		<title>index</title>
		<link rel="stylesheet" type="text/css" href="style.css">
	</head>

	<body class="index">

		<%= button_to "Kit UI complet", kitui_path, :type=>"button", :class=>"btn btn-primary" %>
		<br/>

		<div class="container">
			<div class="row">

    		<div class="col">
					<%= button_to "Navbar", navbar_path, :type=>"button", :class=>"btn btn-primary" %> 
				</div>

    		<div class="col">
					<%= button_to "Sign up Form", signup_path, :type=>"button", :class=>"btn btn-secondary" %> 
    		</div>

    		<div class="col">
					<%= button_to "Log in Form",login_path, :type=>"button", :class=>"btn btn-secondary" %> 
    		</div>
    		  <div class="col">
					<%= button_to "Reset Password Form", resetpassword_path, :type=>"button", :class=>"btn btn-secondary" %> 
    		</div>
			
			<div class="row">
    		<div class="col">
					<%= button_to "Footer", footer_path, :type=>"button", :class=>"btn btn-success" %> 
    		</div>
    	</div>

    		<div class="col">
					<%= button_to "Banner", banner_path, :type=>"button", :class=>"btn btn-info" %> 
				</div>
    		<div class="col">
					<%= button_to "Cards", cards_path, :type=>"button", :class=>"btn btn-warning" %> 
				</div>

				 <div class="col">
					<%= button_to "Comments", comments_path, :type=>"button", :class=>"btn btn-success" %> 
    		</div>
			</div>
	</div>
</body>

app/views/static_pages/login_form.html.erb
<!DOCTYPE html>
<html>

	<head>
		<title>Form</title>


	<link rel="stylesheet" type="text/css" href="style.css">
		
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	</head>

<body>
   <!-- Material form login -->
<center>
<div class="form card">

  <h5 class="card-header text-center py-4">
    <strong>Please sign in</strong>
  </h5>

  <!--Card content-->
  <div class="card-body px-lg-5 pt-0">

    <!-- Form -->
    <form class="text-center" style="color: #757575;" action="#!">
      <!-- Email -->
      <div class="md-form">
      	<br>
        <input type="email" id="materialLoginFormEmail" class="form-control">
        <label for="materialLoginFormEmail">E-mail</label>
      </div>

      <!-- Password -->
      <div class="md-form">
        <input type="password" id="materialLoginFormPassword" class="form-control">
        <label for="materialLoginFormPassword">Password</label>
      </div>

      <div class="d-flex justify-content-around">
        <div>
          <!-- Remember me -->
          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="materialLoginFormRemember">
            <label class="form-check-label" for="materialLoginFormRemember">Remember me</label>
          </div>
        </div>
        <div>
          <!-- Forgot password -->
          <a href="">Forgot password?</a>
        </div>
      </div>

      <!-- Sign in button -->
      <button class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0" type="submit">Sign in</button>

      <!-- Register -->
      <p>Not a member?
        <a href="">Register</a>
      </p>

      <!-- Social login -->
      <p>or sign in with:</p>
    <a href="#" class="mx-2" role="button"><i class="fab fa-facebook-f light-blue-text"></i></a>
    <a href="#" class="mx-2" role="button"><i class="fab fa-twitter light-blue-text"></i></a>
    <a href="#" class="mx-2" role="button"><i class="fab fa-linkedin-in light-blue-text"></i></a>
    <a href="#" class="mx-2" role="button"><i class="fab fa-github light-blue-text"></i></a>

    </form>
    <!-- Form -->

  </div>

</div>
<!-- Material form login -->
</body>

app/views/static_pages/navbar.html.erb
<head>
	<title>Navbar</title>


<!-- // jQuery library -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity=
"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
crossorigin="anonymous"></script>

<!-- // JS library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
crossorigin="anonymous"></script>

<!-- // Latest compiled JavaScript library -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
crossorigin="anonymous"></script>


	<link rel="stylesheet" type="text/css" href="style.css">

</head>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Eventbrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">My city</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Create an event</a>
      </li>
    </ul>
    
    <ul class="navbar-nav ">
    	<div class = "nav-right">
    	<li class="nav-item active">
		    <form class="form-inline my-2 my-lg-0">
		      <input class="form-control mr-sm-2" type="text" placeholder="What'up?">
		      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
		    </form>
		  </li>

		  <li style="margin-left: 10px" class="nav-item active">
				<div class="dropdown">
			  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			    Who are you?
			  </button>
			  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			    <a class="dropdown-item" href="#">Log in</a>
			    <a class="dropdown-item" href="#">Sign up</a>
			    <a class="dropdown-item" href="#">Da fuck u care?</a>
			  </div>
			</div>
		</li>
	</ul>

  </div>
</nav>

app/views/static_pages/signup_form.html.erb
<!DOCTYPE html>
<html>

	<head>
		<title>Form</title>


	<link rel="stylesheet" type="text/css" href="style.css">
		
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	</head>

<body>

  <!-- Material form register -->
<center>
<div class="form card">
    <h5 class="card-header info-color white-text text-center py-4">
        <strong>Please sign up</strong>
    </h5>

    <!--Card content-->
    <div class="card-body px-lg-5 pt-0">

        <!-- Form -->
        <form class="text-center" style="color: #757575;" action="#!">
        <br>
            <div class="form-row">
                <div class="col">
                    <!-- First name -->
                    <div class="md-form">
                      
                        <input type="text" id="materialRegisterFormFirstName" class="form-control">
                        <label for="materialRegisterFormFirstName">First name</label>
                    </div>
                </div>
                <div class="col">
                    <!-- Last name -->
                    <div class="md-form">
                        <input type="email" id="materialRegisterFormLastName" class="form-control">
                        <label for="materialRegisterFormLastName">Last name</label>
                    </div>
                </div>
            </div>

            <!-- E-mail -->
            <div class="md-form mt-0">
                <input type="email" id="materialRegisterFormEmail" class="form-control">
                <label for="materialRegisterFormEmail">E-mail</label>
            </div>

            <!-- Password -->
            <div class="md-form">
                <input type="password" id="materialRegisterFormPassword" class="form-control" aria-describedby="materialRegisterFormPasswordHelpBlock">
                <label for="materialRegisterFormPassword">Password</label>
                <small id="materialRegisterFormPasswordHelpBlock" class="form-text text-muted mb-4">
                    At least 8 characters and 1 digit
                </small>
            </div>

            <!-- Phone number -->
            <div class="md-form">
                <input type="password" id="materialRegisterFormPhone" class="form-control" aria-describedby="materialRegisterFormPhoneHelpBlock">
                <label for="materialRegisterFormPhone">Phone number</label>
                <small id="materialRegisterFormPhoneHelpBlock" class="form-text text-muted mb-4">
                    Optional - for two step authentication
                </small>
            </div>

            <!-- Newsletter -->
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="materialRegisterFormNewsletter">
                <label class="form-check-label" for="materialRegisterFormNewsletter">Subscribe to our newsletter</label>
            </div>

            <!-- Sign up button -->
            <button class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0" type="submit">Sign up</button>

            <!-- Social register -->
            <p>or sign up with:</p>

            <a type="button" class="btn-floating btn-fb btn-sm">
                <i class="fab fa-facebook-f"></i>
            </a>
            <a type="button" class="btn-floating btn-tw btn-sm">
                <i class="fab fa-twitter"></i>
            </a>
            <a type="button" class="btn-floating btn-li btn-sm">
                <i class="fab fa-linkedin-in"></i>
            </a>
            <a type="button" class="btn-floating btn-git btn-sm">
                <i class="fab fa-github"></i>
            </a>

            <hr>

            <!-- Terms of service -->
            <p>By clicking
                <em>Sign up</em> you agree to our
                <a href="" target="_blank">terms of service</a>

        </form>
        <!-- Form -->

    </div>

</div>
<!-- Material form register -->